package dev.thiagosindra.cloudlug.security

import android.content.Context
import android.content.SharedPreferences
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.util.Base64
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * §8.3's credential storage: AES-GCM, with the key generated in and never
 * leaving Android Keystore.
 *
 * The ciphertext lives in ordinary preferences, which is safe precisely because
 * the key does not: an attacker with the file has an opaque blob, and the key
 * that would open it is held by hardware that will not export it. Storing the
 * ciphertext somewhere more exotic would add ceremony without adding secrecy.
 *
 * `setUserAuthenticationRequired(false)` is deliberate and §8.3 says so: a
 * background transfer has to refresh a token while the phone is locked and its
 * owner is asleep. Requiring authentication would mean a transfer that stops
 * every four hours until someone unlocks the device, which is not a security
 * property anyone asked for.
 *
 * ### Why a failure to decrypt returns null rather than throwing
 *
 * Keystore keys are destroyed by events outside this app's control — a factory
 * reset, a restored backup, some OEM behaviour on lock-screen changes. When
 * that happens the stored bytes are permanently unreadable, and the honest
 * answer is "there is no credential here", which sends the user through §8.1's
 * flow again. Throwing would turn a recoverable reconnect into a crash.
 *
 * ### ...and why it says so on the way out
 *
 * Returning null quietly would make three different situations identical to
 * everything above this class: nothing was ever stored, the Keystore key was
 * destroyed, and someone edited the preferences file. The recovery is the same
 * for all three — reconnect — but they are not the same event, and the last one
 * is worth noticing. So each unreadable credential is announced to a
 * [SecretStoreListener], which by default logs at warning level. The
 * announcement carries the storage key and a failure class and nothing else:
 * §26 forbids logging credential material, and there is no diagnostic value in
 * it anyway.
 */
class KeystoreSecretStore(
    context: Context,
    private val preferencesName: String = DEFAULT_PREFERENCES,
    private val keyAlias: String = DEFAULT_KEY_ALIAS,
    private val listener: SecretStoreListener = SecretStoreListener.Logging,
) : SecretStore {

    private val preferences: SharedPreferences =
        context.applicationContext.getSharedPreferences(preferencesName, Context.MODE_PRIVATE)

    private val keyStore: KeyStore = KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }

    override fun put(key: String, secret: String) {
        val cipher = Cipher.getInstance(TRANSFORMATION).apply { init(Cipher.ENCRYPT_MODE, secretKey()) }
        val ciphertext = cipher.doFinal(secret.toByteArray(Charsets.UTF_8))

        // The IV is generated by the cipher, never reused, and stored beside
        // the ciphertext: GCM's security depends on never encrypting twice
        // under the same key and IV, which is exactly why it is not chosen here.
        val payload = cipher.iv + ciphertext
        preferences.edit().putString(key, Base64.encodeToString(payload, Base64.NO_WRAP)).apply()
    }

    override fun get(key: String): String? {
        // Absent is absent: no listener, no log. Every caller starts here on a
        // fresh install, and a warning on the ordinary path teaches people to
        // ignore the warning.
        val stored = preferences.getString(key, null) ?: return null

        val payload = runCatching { Base64.decode(stored, Base64.NO_WRAP) }.getOrNull()
        if (payload == null || payload.size <= IV_BYTES) {
            return unreadable(key, UnreadableReason.Malformed)
        }

        // Deliberately *not* secretKey(): that one generates a key when none is
        // found, which here would manufacture a key incapable of reading the
        // bytes beside it and report the destroyed key as a failed tag — the
        // precise confusion this reporting exists to avoid.
        val cipherKey = existingKey() ?: return unreadable(key, UnreadableReason.KeystoreKeyMissing)

        return runCatching {
            val cipher = Cipher.getInstance(TRANSFORMATION).apply {
                init(Cipher.DECRYPT_MODE, cipherKey, GCMParameterSpec(TAG_BITS, payload, 0, IV_BYTES))
            }
            String(cipher.doFinal(payload, IV_BYTES, payload.size - IV_BYTES), Charsets.UTF_8)
        }.getOrElse { failure ->
            // The class name, never the message: an exception's message is
            // written by someone else and could carry anything.
            unreadable(key, UnreadableReason.DecryptionFailed(failure.javaClass.simpleName))
        }
    }

    override fun remove(key: String) {
        preferences.edit().remove(key).apply()
    }

    override fun clear() {
        preferences.edit().clear().apply()
        // The key goes too. Leaving it would keep material alive that nothing
        // can decrypt any more, and §8.3's disconnect is meant to leave nothing.
        runCatching { keyStore.deleteEntry(keyAlias) }
    }

    private fun unreadable(key: String, reason: UnreadableReason): String? {
        listener.onUnreadableSecret(key, reason)
        return null
    }

    /** The stored key, or null when there is none; never creates one. */
    private fun existingKey(): SecretKey? =
        runCatching { keyStore.getEntry(keyAlias, null) as? KeyStore.SecretKeyEntry }
            .getOrNull()
            ?.secretKey

    /** Generated on first use and reused thereafter; never leaves Keystore. */
    private fun secretKey(): SecretKey {
        existingKey()?.let { return it }

        val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, ANDROID_KEYSTORE)
        generator.init(
            KeyGenParameterSpec.Builder(
                keyAlias,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                // §8.3: background refresh must work on a locked phone.
                .setUserAuthenticationRequired(false)
                .build(),
        )
        return generator.generateKey()
    }

    private companion object {
        const val ANDROID_KEYSTORE = "AndroidKeyStore"
        const val TRANSFORMATION = "AES/GCM/NoPadding"
        const val DEFAULT_PREFERENCES = "cloudlug-credentials"
        const val DEFAULT_KEY_ALIAS = "cloudlug-credential-key"

        /** GCM's standard 96-bit nonce, which is what the cipher generates. */
        const val IV_BYTES = 12
        const val TAG_BITS = 128
    }
}
